version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: validate_service.sh
      timeout: 300
  
